name: Arduino CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: true
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python serial library
        run: python -m pip install pyserial

      - name: Install Arduino CLI
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

      - name: Install Arduino ESP32 Devkit
        run: ./bin/arduino-cli core install esp32:esp32

      - name: Build Jessy OS via Arduino CLI
        run: |
          ./bin/arduino-cli compile --fqbn esp32:esp32:esp32wrover --library lib/Arduino-List --library lib/FabGL --library lib/rishka --build-path build --verbose kernel
