name: Arduino CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Python serial library
        run: python3 -m pip install pyserial

      - name: Arduino ESP32 Platform Installation
        run: arduino-cli core install esp32:esp32

      - name: Pull all library submodules
        run: git submodule update --recursive --remote

      - name: Build Jessy OS via Arduino CLI
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32wrover --library lib/Arduino-List --library lib/fabgl --library lib/rishka --build-path build kernel
